// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[installation]]
= Installing Gradle

[[gs:installation]]
== Gradle Installation

* if you ONLY want to run a project / exist <<gradle_wrapper#gradle_wrapper_reference,Gradle Wrapper>> ->
    ** NOT need to install Gradle
    ** check your system <<installation#sec:prerequisites,satisfies Gradle's prerequisites>>

[listing,subs=+macros]
----
.   // <1>
â”œâ”€â”€ gradle
â”‚   â””â”€â”€ wrapper // <2>
â”œâ”€â”€ gradlew         // <3>
â”œâ”€â”€ gradlew.bat     // <3>
â””â”€â”€ â‹®
----

* ðŸ‘ï¸built-in installed with Android Studio ðŸ‘ï¸
    ** -> NOT need to install Gradle
* link:{website}/releases[Gradle releases]

[[sec:prerequisites]]
== Prerequisites

* link:{jdkDownloadUrl}[Java Development Kit] (JDK)
    ** {minJdkVersion} +
    ** check the <<compatibility.adoc#compatibility,compatibility matrix>>
    ** set environment variable
        *** `JAVA_HOME`
        *** | `PATH`
* Gradle comes with built-in (-> NOT need to install it) libraries
    ** link:https://kotlinlang.org/[Kotlin]
    ** link:https://groovy-lang.org/[Groovy]
* <<compatibility.adoc#compatibility, Compatibility notes for Java, Groovy, Kotlin, and Android.>>

== Linux installation

* via
    ** package manager
        *** link:http://sdkman.io[SDKMAN!]
            **** == tool / manage parallel versions of multiple SDK | most Unix-like systems
            **** `sdk install gradle`
        *** others
            **** -- NOT controlled by -- Gradle, Inc.
    ** manually
        *** link:{website}/releases[Download] the latest Gradle distribution**
            **** flavors
                ***** Binary-only (bin) -- recommended --
                ***** Complete
        *** Unpack the distribution
            **** Check [[sec:linux_macos_users_2]]
        *** Configure your system environment
            **** `export PATH=$PATH:/opt/gradle/gradle-{gradleVersion}/bin`
            **** with 2

                    export GRADLE_HOME=/opt/gradle/gradle-{gradleVersion}
                    export PATH=${GRADLE_HOME}/bin:${PATH}


== macOS installation

* via
    ** package manager
        *** link:http://sdkman.io[SDKMAN!]
            **** `sdk install gradle`
        *** link:http://brew.sh[Homebrew]
            **** `brew install gradle`
        *** link:https://www.macports.org[MacPorts]
            **** `sudo port install gradle`
        *** others
            *** -- NOT controlled by -- Gradle, Inc.
    ** Installing manually
* TODO:

**Step 1 - link:{website}/releases[Download] the latest Gradle distribution**

The distribution ZIP file comes in two flavors:

- Binary-only (bin)
- Complete (all) with docs and sources

We recommend downloading the bin file; it is a smaller file that is quick to download (and the latest documentation is available online).

**Step 2 - Unpack the distribution**

Unzip the distribution zip file in the directory of your choosing, e.g.:

[subs="attributes"]
----
â¯ mkdir /usr/local/gradle
â¯ unzip gradle-{gradleVersion}-bin.zip -d /usr/local/gradle
â¯ ls /usr/local/gradle/gradle-{gradleVersion}
LICENSE	NOTICE	README	bin	init.d	lib
----

**Step 3 - Configure your system environment**

To install Gradle, the path to the unpacked files needs to be in your Path.
Configure your `PATH` environment variable to include the `bin` directory of the unzipped distribution, e.g.:

[subs="attributes"]
----
â¯ export PATH=$PATH:/usr/local/gradle/gradle-{gradleVersion}/bin
----

Alternatively, you could also add the environment variable `GRADLE_HOME` and point this to the unzipped distribution.
Instead of adding a specific version of Gradle to your `PATH`, you can add `$GRADLE_HOME/bin` to your `PATH`.
When upgrading to a different version of Gradle, simply change the `GRADLE_HOME` environment variable.

It's a good idea to edit `.bash_profile` in your home directory to add `GRADLE_HOME` variable:

[subs="attributes"]
----
export GRADLE_HOME=/usr/local/gradle/gradle-{gradleVersion}
export PATH=$GRADLE_HOME/bin:$PATH
----

== Windows installation

.Installing manually
[%collapsible]
====

**Step 1 - link:{website}/releases[Download] the latest Gradle distribution**

The distribution ZIP file comes in two flavors:

- Binary-only (bin)
- Complete (all) with docs and sources

We recommend downloading the bin file.

**Step 2 - Unpack the distribution**

Create a new directory `C:\Gradle` with **File Explorer**.

Open a second **File Explorer** window and go to the directory where the Gradle distribution was downloaded. Double-click the ZIP archive to expose the content.
Drag the content folder `gradle-{gradleVersion}` to your newly created `C:\Gradle` folder.

Alternatively, you can unpack the Gradle distribution ZIP into `C:\Gradle` using the archiver tool of your choice.

**Step 3 - Configure your system environment**

To install Gradle, the path to the unpacked files needs to be in your Path.

In **File Explorer** right-click on the `This PC` (or `Computer`) icon, then click `Properties` -> `Advanced System Settings` -> `Environmental Variables`.

Under `System Variables` select `Path`, then click `Edit`.
Add an entry for `C:\Gradle\gradle-{gradleVersion}\bin`.
Click `OK` to save.

Alternatively, you can add the environment variable `GRADLE_HOME` and point this to the unzipped distribution.
Instead of adding a specific version of Gradle to your `Path`, you can add `__%GRADLE_HOME%__\bin` to your `Path`.
When upgrading to a different version of Gradle, just change the `GRADLE_HOME` environment variable.
====

[[sec:running_and_testing_your_installation]]
== Verify the installation

* `gradle -v`
* download the SHA-256 file | link:{website}/releases[releases page]
* follow <<gradle_wrapper.adoc#sec:verification,verification instructions>>
